/*
 * Created on 22 Dec 2015 ( Time 09:23:11 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.webbook.web.controller;

import java.util.List;
import java.util.ArrayList;
import java.util.Date;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import javax.validation.Valid;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.trams.webbook.web.common.AbstractController;
import org.trams.webbook.web.common.ApplicationDefine;
import org.trams.webbook.web.common.FormMode;
import org.trams.webbook.web.common.Pager;
import org.trams.webbook.web.common.Login;
import org.trams.webbook.web.common.Message;
import org.trams.webbook.web.common.MessageType;
import org.trams.webbook.bean.jpa.CommentEntity;
import org.trams.webbook.bean.jpa.PostEntity;
import org.trams.webbook.bean.Comment;
//--- Entities
import org.trams.webbook.bean.Post;
import org.trams.webbook.bean.User;
import org.trams.webbook.business.service.CommentService;
//--- Services 
import org.trams.webbook.business.service.PostService;
import org.trams.webbook.business.service.mapping.PostServiceMapper;


/**
 * Spring MVC controller for 'Post' management.
 */
@Controller
@RequestMapping("/community/faq")
public class FAQController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "post";
	private static final String MAIN_LIST_NAME = "list";

	private static final String TOTAL_PAGE   = "pages";

	private static final String CURRENT_PAGE   = "pageNumber";

	private static final String LIST_PAGES   = "listPages";

	private static final Integer PAGE_SIZE   = 16;

	private static String nav = "community";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_CREATE   = "faq/create";
	private static final String JSP_LIST   = "faq/list";
	private static final String JSP_PAGING   = "faq";
	private static final String JSP_EDIT   = "faq/edit";
	private static final String JSP_DETAIL   = "faq/detail";
	private static final String JSP_LOGIN   = "redirect:/login";

	//--- Main entity service
	@Resource
    private PostService postService; // Injected by Spring
	@Resource
	private PostServiceMapper postServiceMapper;
	@Resource
	private CommentService commentService;
	//--- Other service(s)

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public FAQController() {
		super(FAQController.class, MAIN_ENTITY_NAME );
		log("PostController created.");
	}

	//Decription:get list faq
	//Url: 		 http://kwebsosul.com/community/faq
	@RequestMapping("")
	public String list(
			@RequestParam(value="page",defaultValue="1") Integer page,
			HttpSession session,
			Model model) {

		Page<PostEntity> listPage = null;
		listPage=postService.findByBulletin(12, page, PAGE_SIZE, "createDate");
		model.addAttribute(MAIN_LIST_NAME, listPage);	
		model.addAttribute("activePage", nav);
		model.addAttribute("activeMenu", "faq");
		model.addAttribute("pagination_navigator", "/community/faq");
		new Pager<PostEntity>(listPage).setSetting(model, "");		
		return JSP_LIST;
	}
	//Decription:get detail fag 
	//Url: http://kwebsosul.com/community/faq/detail/117
	@RequestMapping("/detail/{id}")
	public String detail(
	@RequestParam(value="comment",defaultValue="0") Integer comment,
	@RequestParam(value="content",defaultValue="") String content,
	@RequestParam(value="delete_comment",defaultValue="0") Integer delete_comment,
	Model model, 
	HttpSession session,
	@PathVariable("id") Integer id) {
	
		User user = Login.getUserLogin(session);
		if(delete_comment>0){
			Comment comment1 =commentService.findById(delete_comment);
			comment1.setIsDelete(1);
			commentService.update(comment1);
		}
		
		if(comment>0 && content.trim()!=""){
			Comment c = new Comment();
			c.setComment(content);
			c.setCreateDate(new Date());
			c.setIsDelete(0);
			c.setParentId(id);
			c.setReportNumber(0);
			c.setTypeKey(ApplicationDefine.COMMENT_POST_TYPE);
			c.setUpdateDate(new Date());
			c.setUserId(user.getId());
			commentService.create(c);
		}
		
		PostEntity postEntity = postService.findOne(id);
		if(postEntity.getViewsNumber()==null){
			postEntity.setViewsNumber(1);
		}else{
			postEntity.setViewsNumber(postEntity.getViewsNumber()+1);
		}
		Post p=postServiceMapper.mapPostEntityToPost(postEntity);
		p=postService.update(p);
		Post post = postServiceMapper.mapPostEntityToPost(postEntity);
		List<CommentEntity> listComment = commentService.findAllBy_ParentId_Type(id, ApplicationDefine.COMMENT_POST_TYPE);
		model.addAttribute("listComment", listComment);
		model.addAttribute("total_comment", listComment.size());
		model.addAttribute("post", postEntity);
		model.addAttribute("activePage", nav);
		model.addAttribute("activeMenu", "faq");
		model.addAttribute("user", user);
		return JSP_DETAIL;
	}
	
	@RequestMapping(value = "/edit/{id}")
	public String update(
	@RequestParam(value="edit",defaultValue="0") Integer edit,
	HttpSession session,
	@PathVariable("id") Integer id,
	Model model  ) {
	if(Login.checkLogin(session)=="0")
			return JSP_LOGIN;
Post post = postService.findById(id);
		try {
			if(edit>0){
				post = postService.update(post);
				post.setUpdateDate(new Date());
				
			}
			model.addAttribute("item", post);
			return JSP_EDIT;
		} catch(Exception e) {
			return JSP_LIST;
		}
	}
	
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(
			@RequestParam(value="create",defaultValue="0") Integer create,
			HttpSession session,
			Model model) {
		log("Action 'create'");
		if(Login.checkLogin(session)=="0")
			return JSP_LOGIN;
		try {
			if(create>0){
			Post post = new Post();
			post.setUpdateDate(new Date());
			post.setCreateDate(new Date());
			postService.update(post);
			}
			return JSP_LIST;
		} catch(Exception e) {
			
			return JSP_CREATE;
		}
	}

	@RequestMapping(value = "/delete/{id}")
	public String delete(
	Model model, 
	HttpSession session,
	@PathVariable("id") Integer id ) {
	if(Login.checkLogin(session)=="0")
			return JSP_LOGIN;
		postService.delete(id);
		return JSP_LIST;
	}

}
