/*

 * Created on 15 Dec 2015 ( Time 14:50:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.webbook.web.controller;

import javax.annotation.Resource;
import javax.servlet.http.HttpSession;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
//--- Common classes
import org.trams.webbook.web.common.AbstractController;
import org.trams.webbook.web.common.Pager;
import org.trams.webbook.web.common.Login;
import org.trams.webbook.bean.jpa.BookEntity;
import org.trams.webbook.web.common.Utils;
//--- Entities
import org.trams.webbook.business.service.BookService;
import org.trams.webbook.business.service.CategoryService;
//--- Services 
import org.trams.webbook.business.service.UserService;

/**
 * Spring MVC controller for 'User' management.
 */
@Controller
@RequestMapping("/league&contest")
public class LeagueContestController extends AbstractController {

	// --- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "user";

	private static final Integer PAGE_SIZE   = 10;

	// --- SAVE ACTION ( in the HTML form )
	private static final String INDEX = "league_contest/index";
	private static String nav = "league";

	// --- Main entity service
	@Resource
	private UserService userService; // Injected by Spring
	// --- Other service(s)
	@Resource
	private CategoryService categoryService;
	@Resource
    private BookService bookService;
	// --------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public LeagueContestController() {
		super(LeagueContestController.class, MAIN_ENTITY_NAME);
		log("LeagueContestController created.");
	}

	// --------------------------------------------------------------------------------------
	// Spring MVC model management
	// --------------------------------------------------------------------------------------
	//Decription: show league&contest page
	//Url: 		http://kwebsosul.com/league&contest
	@RequestMapping("")
	public String index(
			@RequestParam(value="page",defaultValue="1") Integer page,
			@RequestParam(value="age",defaultValue="1") Integer age,
			@RequestParam(value="option",defaultValue="24") String option,
			@RequestParam(value="order",defaultValue="update") String order,
			HttpSession session, Model model) {
		Page<BookEntity> list = null;
		try {
			String orderBy = "updateDate";
			if(order != null){
				if(order.equals("update")){
					orderBy = "updateDate";
				}else if(order.equals("hits")){
					orderBy = "hitsNo";
				}
			}
			list = bookService.searchBoook(page, PAGE_SIZE, age, Utils.parseInt(option), orderBy);
		} catch (Exception e) {
			System.out.println(e);
		}
		model.addAttribute("age", age);
		model.addAttribute("option", option);
		model.addAttribute("order", order);
		model.addAttribute("activePage", nav);
		model.addAttribute("age_list", categoryService.findByGroupId(1));
		new Pager<BookEntity>(list).setSetting(model, "age="+age+"&amp;option="+option+"&amp;order="+order+"&amp;");
		return INDEX;
	}
	
}
