/*
 * Created on 15 Dec 2015 ( Time 14:53:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.webbook.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.trams.webbook.bean.CouponPurchase;
import org.trams.webbook.business.service.CouponPurchaseService;
import org.trams.webbook.web.listitem.CouponPurchaseListItem;

/**
 * Spring MVC controller for 'CouponPurchase' management.
 */
@Controller
public class CouponPurchaseRestController {

	@Resource
	private CouponPurchaseService couponPurchaseService;
	
	@RequestMapping( value="/api/items/couponPurchase",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<CouponPurchaseListItem> findAllAsListItems() {
		List<CouponPurchase> list = couponPurchaseService.findAll();
		List<CouponPurchaseListItem> items = new LinkedList<CouponPurchaseListItem>();
		for ( CouponPurchase couponPurchase : list ) {
			items.add(new CouponPurchaseListItem( couponPurchase ) );
		}
		return items;
	}
	
	@RequestMapping( value="/api/couponPurchase",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<CouponPurchase> findAll() {
		return couponPurchaseService.findAll();
	}

	@RequestMapping( value="/api/couponPurchase/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public CouponPurchase findOne(@PathVariable("id") Integer id) {
		return couponPurchaseService.findById(id);
	}
	
	@RequestMapping( value="/api/couponPurchase",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public CouponPurchase create(@RequestBody CouponPurchase couponPurchase) {
		return couponPurchaseService.create(couponPurchase);
	}

	@RequestMapping( value="/api/couponPurchase/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public CouponPurchase update(@PathVariable("id") Integer id, @RequestBody CouponPurchase couponPurchase) {
		return couponPurchaseService.update(couponPurchase);
	}

	@RequestMapping( value="/api/couponPurchase/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Integer id) {
		couponPurchaseService.delete(id);
	}
	
}
