/*
 * Created on 11 Jan 2016 ( Time 16:14:57 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.webbook.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.trams.webbook.bean.Banner;
import org.trams.webbook.bean.jpa.BannerEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class BannerServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public BannerServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'BannerEntity' to 'Banner'
	 * @param bannerEntity
	 */
	public Banner mapBannerEntityToBanner(BannerEntity bannerEntity) {
		if(bannerEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Banner banner = map(bannerEntity, Banner.class);

		return banner;
	}
	
	/**
	 * Mapping from 'Banner' to 'BannerEntity'
	 * @param banner
	 * @param bannerEntity
	 */
	public void mapBannerToBannerEntity(Banner banner, BannerEntity bannerEntity) {
		if(banner == null) {
			return;
		}

		//--- Generic mapping 
		map(banner, bannerEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}