/*
 * Created on 12 Jan 2016 ( Time 15:24:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.webbook.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.trams.webbook.bean.ProfitRefund;
import org.trams.webbook.bean.jpa.ProfitRefundEntity;
import org.trams.webbook.bean.jpa.UserEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class ProfitRefundServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public ProfitRefundServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'ProfitRefundEntity' to 'ProfitRefund'
	 * @param profitRefundEntity
	 */
	public ProfitRefund mapProfitRefundEntityToProfitRefund(ProfitRefundEntity profitRefundEntity) {
		if(profitRefundEntity == null) {
			return null;
		}

		//--- Generic mapping 
		ProfitRefund profitRefund = map(profitRefundEntity, ProfitRefund.class);

		//--- Link mapping ( link to User )
		if(profitRefundEntity.getUser() != null) {
			profitRefund.setUserId(profitRefundEntity.getUser().getId());
		}
		return profitRefund;
	}
	
	/**
	 * Mapping from 'ProfitRefund' to 'ProfitRefundEntity'
	 * @param profitRefund
	 * @param profitRefundEntity
	 */
	public void mapProfitRefundToProfitRefundEntity(ProfitRefund profitRefund, ProfitRefundEntity profitRefundEntity) {
		if(profitRefund == null) {
			return;
		}

		//--- Generic mapping 
		map(profitRefund, profitRefundEntity);

		//--- Link mapping ( link : profitRefund )
		if( hasLinkToUser(profitRefund) ) {
			UserEntity user1 = new UserEntity();
			user1.setId( profitRefund.getUserId() );
			profitRefundEntity.setUser( user1 );
		} else {
			profitRefundEntity.setUser( null );
		}

	}
	
	/**
	 * Verify that User id is valid.
	 * @param User User
	 * @return boolean
	 */
	private boolean hasLinkToUser(ProfitRefund profitRefund) {
		if(profitRefund.getUserId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}