/*
 * Created on 15 Dec 2015 ( Time 17:20:39 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.webbook.business.service;

import java.util.List;
import org.trams.webbook.bean.jpa.BannerEntity;
import org.trams.webbook.bean.Banner;
import org.springframework.data.domain.Page;

/**
 * Business Service Interface for entity Banner.
 */
public interface BannerService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Banner findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<Banner> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<BannerEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Banner save(Banner entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Banner update(Banner entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Banner create(Banner entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );
	
	Page<BannerEntity> listPaging(Integer page,Integer size);

}
