/*
 * Created on 16 Jan 2016 ( Time 10:42:16 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.webbook.business.service;

import java.util.List;
import org.trams.webbook.bean.jpa.BookViewingEntity;
import org.trams.webbook.bean.BookViewing;
import org.springframework.data.domain.Page;

/**
 * Business Service Interface for entity BookViewing.
 */
public interface BookViewingService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	BookViewing findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<BookViewing> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<BookViewingEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	BookViewing save(BookViewing entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	BookViewing update(BookViewing entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	BookViewing create(BookViewing entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );
	
	Page<BookViewingEntity> listPaging(Integer page,Integer size);
	List<BookViewingEntity> findBy_UserId(Integer userId);
}
