/*
 * Created on 2 Mar 2016 ( Time 11:54:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.webbook.business.service;

import java.util.List;
import org.trams.webbook.bean.jpa.ContactUsEntity;
import org.trams.webbook.bean.ContactUs;
import org.springframework.data.domain.Page;

/**
 * Business Service Interface for entity ContactUs.
 */
public interface ContactUsService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	ContactUs findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<ContactUs> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<ContactUsEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	ContactUs save(ContactUs entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	ContactUs update(ContactUs entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	ContactUs create(ContactUs entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );
	
	ContactUsEntity findOne(Integer id);
	
	Page<ContactUsEntity> listPaging(Integer page,Integer size);

}
