/*
 * Created on 7 Jan 2016 ( Time 14:53:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.webbook.business.service;

import java.awt.print.Pageable;
import java.util.Date;
import java.util.List;
import org.trams.webbook.bean.jpa.CouponUsedEntity;
import org.trams.webbook.bean.jpa.PostEntity;
import org.trams.webbook.bean.CouponUsed;
import org.apache.commons.io.CopyUtils;
import org.springframework.data.domain.Page;

/**
 * Business Service Interface for entity CouponUsed.
 */
public interface CouponUsedService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	CouponUsed findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<CouponUsed> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<CouponUsedEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	CouponUsed save(CouponUsed entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	CouponUsed update(CouponUsed entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	CouponUsed create(CouponUsed entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );
	
	Page<CouponUsedEntity> listPaging(Integer page,Integer size);
	
	CouponUsedEntity findBy_UserId_EpisodeId(Integer userId, Integer episodeId);

	Page<CouponUsedEntity> listPagingSearch(String id, String name, Integer page, Integer size);
	
	Page<CouponUsedEntity> listPagingSearchSales(String id, String name, String bookname, String episodename ,Integer page, Integer size);
	
	Integer totalCouponChargingAmount(Date from, Date to);
	
	Integer totalCouponUser(Date from, Date to);
	
	Integer totalPriceCoupon(Integer year, Integer month);
	
	List<CouponUsedEntity> listBy_UserId(Integer userId);

	CouponUsedEntity findOne(Integer id);
	
	Page<CouponUsedEntity> listPagingBy_AuthorId_Month_Year(Integer userid,Integer month, Integer year,Integer page, Integer size);
	
	Integer totalChargeAmountBy_UserId(Integer userid);
	
	List<CouponUsedEntity> findBy_UserId_BookId(Integer userId, Integer bookId);
	
	List<CouponUsedEntity> listBy_AuthorId_Month_Year(Integer userid,Integer month, Integer year, Integer page, Integer size);
	
	Integer totalPageBy_AuthorId_Month_Year(Integer userid,Integer month, Integer year);
}
