/*
 * Created on 11 Jan 2016 ( Time 16:14:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.trams.webbook.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "banner"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="banner", catalog="webbook" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="BannerEntity.countAll", query="SELECT COUNT(x) FROM BannerEntity x" )
} )
public class BannerEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="_id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="BANNER_1", length=500)
    private String     banner1      ;

    @Column(name="BANNER_2", length=500)
    private String     banner2      ;

    @Column(name="BANNER_3", length=500)
    private String     banner3      ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE")
    private Date       createDate   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE")
    private Date       updateDate   ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public BannerEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : BANNER_1 ( VARCHAR ) 
    public void setBanner1( String banner1 ) {
        this.banner1 = banner1;
    }
    public String getBanner1() {
        return this.banner1;
    }

    //--- DATABASE MAPPING : BANNER_2 ( VARCHAR ) 
    public void setBanner2( String banner2 ) {
        this.banner2 = banner2;
    }
    public String getBanner2() {
        return this.banner2;
    }

    //--- DATABASE MAPPING : BANNER_3 ( VARCHAR ) 
    public void setBanner3( String banner3 ) {
        this.banner3 = banner3;
    }
    public String getBanner3() {
        return this.banner3;
    }

    //--- DATABASE MAPPING : CREATE_DATE ( DATETIME ) 
    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    //--- DATABASE MAPPING : UPDATE_DATE ( DATETIME ) 
    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(banner1);
        sb.append("|");
        sb.append(banner2);
        sb.append("|");
        sb.append(banner3);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(updateDate);
        return sb.toString(); 
    } 

}
