/*
 * Created on 11 Jan 2016 ( Time 16:14:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.trams.webbook.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "category"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="category", catalog="webbook" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="CategoryEntity.countAll", query="SELECT COUNT(x) FROM CategoryEntity x" )
} )
public class CategoryEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="_id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="catName", nullable=false, length=200)
    private String     catname      ;

    @Column(name="Description", length=200)
    private String     description  ;

    @Column(name="GroupId")
    private Integer    groupid      ;

    @Column(name="groupName", length=200)
    private String     groupname    ;

    @Column(name="catId")
    private Integer    catid        ;

    @Column(name="image", length=500)
    private String     image        ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createDate")
    private Date       createdate   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updateDate")
    private Date       updatedate   ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public CategoryEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : catName ( VARCHAR ) 
    public void setCatname( String catname ) {
        this.catname = catname;
    }
    public String getCatname() {
        return this.catname;
    }

    //--- DATABASE MAPPING : Description ( VARCHAR ) 
    public void setDescription( String description ) {
        this.description = description;
    }
    public String getDescription() {
        return this.description;
    }

    //--- DATABASE MAPPING : GroupId ( INT ) 
    public void setGroupid( Integer groupid ) {
        this.groupid = groupid;
    }
    public Integer getGroupid() {
        return this.groupid;
    }

    //--- DATABASE MAPPING : groupName ( VARCHAR ) 
    public void setGroupname( String groupname ) {
        this.groupname = groupname;
    }
    public String getGroupname() {
        return this.groupname;
    }

    //--- DATABASE MAPPING : catId ( INT ) 
    public void setCatid( Integer catid ) {
        this.catid = catid;
    }
    public Integer getCatid() {
        return this.catid;
    }

    //--- DATABASE MAPPING : image ( VARCHAR ) 
    public void setImage( String image ) {
        this.image = image;
    }
    public String getImage() {
        return this.image;
    }

    //--- DATABASE MAPPING : createDate ( DATETIME ) 
    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    //--- DATABASE MAPPING : updateDate ( DATETIME ) 
    public void setUpdatedate( Date updatedate ) {
        this.updatedate = updatedate;
    }
    public Date getUpdatedate() {
        return this.updatedate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(catname);
        sb.append("|");
        sb.append(description);
        sb.append("|");
        sb.append(groupid);
        sb.append("|");
        sb.append(groupname);
        sb.append("|");
        sb.append(catid);
        sb.append("|");
        sb.append(image);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(updatedate);
        return sb.toString(); 
    } 

}
