/*
 * Created on 11 Jan 2016 ( Time 16:14:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.trams.webbook.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "coupon_used"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="coupon_used", catalog="webbook" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="CouponUsedEntity.countAll", query="SELECT COUNT(x) FROM CouponUsedEntity x" )
} )
public class CouponUsedEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="_id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="CHARGE_AMOUNT")
    private Integer    chargeAmount ;

    @Column(name="METHOD_PAYMENT")
    private Integer    methodPayment ;

    @Column(name="IS_DELETE")
    private Integer    isDelete     ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_DATE")
    private Date       createDate   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE")
    private Date       updateDate   ;

	// "userId" (column "USER_ID") is not defined by itself because used as FK in a link 
	// "episodeId" (column "EPISODE_ID") is not defined by itself because used as FK in a link 
	// "bookId" (column "BOOK_ID") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="USER_ID", referencedColumnName="_id")
    private UserEntity user        ;

    @ManyToOne
    @JoinColumn(name="EPISODE_ID", referencedColumnName="_id")
    private EpisodeEntity episode     ;

    @ManyToOne
    @JoinColumn(name="BOOK_ID", referencedColumnName="_id")
    private BookEntity book        ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public CouponUsedEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : CHARGE_AMOUNT ( INT ) 
    public void setChargeAmount( Integer chargeAmount ) {
        this.chargeAmount = chargeAmount;
    }
    public Integer getChargeAmount() {
        return this.chargeAmount;
    }

    //--- DATABASE MAPPING : METHOD_PAYMENT ( INT ) 
    public void setMethodPayment( Integer methodPayment ) {
        this.methodPayment = methodPayment;
    }
    public Integer getMethodPayment() {
        return this.methodPayment;
    }

    //--- DATABASE MAPPING : IS_DELETE ( INT ) 
    public void setIsDelete( Integer isDelete ) {
        this.isDelete = isDelete;
    }
    public Integer getIsDelete() {
        return this.isDelete;
    }

    //--- DATABASE MAPPING : CREATE_DATE ( DATETIME ) 
    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    //--- DATABASE MAPPING : UPDATE_DATE ( DATETIME ) 
    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setUser( UserEntity user ) {
        this.user = user;
    }
    public UserEntity getUser() {
        return this.user;
    }

    public void setEpisode( EpisodeEntity episode ) {
        this.episode = episode;
    }
    public EpisodeEntity getEpisode() {
        return this.episode;
    }

    public void setBook( BookEntity book ) {
        this.book = book;
    }
    public BookEntity getBook() {
        return this.book;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(chargeAmount);
        sb.append("|");
        sb.append(methodPayment);
        sb.append("|");
        sb.append(isDelete);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(updateDate);
        return sb.toString(); 
    } 

}
