/*
 * Created on 16 Jan 2016 ( Time 10:42:01 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.webbook.web.listitem;

import org.trams.webbook.bean.BookViewing;
import org.trams.webbook.web.common.ListItem;

public class BookViewingListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public BookViewingListItem(BookViewing bookViewing) {
		super();

		this.value = ""
			 + bookViewing.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = bookViewing.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
