/*
 * Created on 21 Jan 2016 ( Time 13:45:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.webbook.web.listitem;

import org.trams.webbook.bean.Post;
import org.trams.webbook.web.common.ListItem;

public class PostListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public PostListItem(Post post) {
		super();

		this.value = ""
			 + post.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = post.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
