/*
 * Created on 12 Jan 2016 ( Time 15:23:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.webbook.web.listitem;

import org.trams.webbook.bean.User;
import org.trams.webbook.web.common.ListItem;

public class UserListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public UserListItem(User user) {
		super();

		this.value = ""
			 + user.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = user.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
