/*
 * Created on 22 Dec 2015 ( Time 09:23:10 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.webbook.web.admin.controller;

import java.util.List;
import java.util.ArrayList;
import java.util.Date;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import javax.validation.Valid;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.trams.webbook.web.common.AbstractController;
import org.trams.webbook.web.common.FormMode;
import org.trams.webbook.web.common.Pager;
import org.trams.webbook.web.common.Login;
import org.trams.webbook.web.common.Message;
import org.trams.webbook.web.common.MessageType;
import org.trams.webbook.bean.jpa.AnnouncementEntity;
import org.trams.webbook.bean.jpa.BookEntity;
//--- Entities
import org.trams.webbook.bean.Announcement;
import org.trams.webbook.bean.Book;
import org.trams.webbook.bean.Episode;
//--- Services 
import org.trams.webbook.business.service.AnnouncementService;
import org.trams.webbook.business.service.BookService;


/**
 * Spring MVC controller for 'Announcement' management.
 */
@Controller
@RequestMapping("/admin/announcement")
public class AnnouncementAdminController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "announcement";
	private static final String MAIN_LIST_NAME = "list";

	private static final String TOTAL_PAGE   = "pages";

	private static final String CURRENT_PAGE   = "pageNumber";

	private static final String LIST_PAGES   = "listPages";

	private static final Integer PAGE_SIZE   = 15;

	private static String nav = "announcement";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_CREATE   = "admin/announcement/create";
	private static final String JSP_LIST   = "admin/announcement/list";
	private static final String JSP_PAGING   = "admin/announcement";
	private static final String JSP_EDIT   = "admin/announcement/edit";
	private static final String JSP_DETAIL   = "admin/announcement/detail";
	private static final String JSP_LOGIN   = "redirect:/admin/login";

	//--- Main entity service
	@Resource
    private AnnouncementService announcementService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private BookService bookService;
	//--- Other service(s)

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public AnnouncementAdminController() {
		super(AnnouncementAdminController.class, MAIN_ENTITY_NAME );
		log("AnnouncementAdminController created.");
	}


	//Decription: Get detail announcement
	//Url: http://kwebsosul.com/admin/announcement/detail/{id}
	@RequestMapping(value = "/detail/{id}")
	public String detail(
	@RequestParam(value="delete",defaultValue="0") Integer delete,
	HttpSession session,
	@PathVariable("id") Integer id,
	Model model  ) {
		if(Login.checkAdminLogin(session)=="0")
			return JSP_LOGIN;
		Announcement e = announcementService.findById(id);
		BookEntity book = bookService.findOne(e.getBookId());
		try {
			if(delete>0){
				Announcement announcement = announcementService.findById(id);
				announcement.setIsDelete(1);
				announcementService.update(announcement);
				return "redirect:/admin/book/detail/"+book.getId();
			}
			model.addAttribute("book", book);
			model.addAttribute("e", e);
			return JSP_DETAIL;
		} catch(Exception ex) {
			return JSP_LIST;
		}
	}
	//Decription: edit announcement
	//Url: http://kwebsosul.com/admin/announcement/edit/{id}
	@RequestMapping(value = "/edit/{id}")
	public String update(
	@RequestParam(value="edit",defaultValue="0") Integer edit,
	@RequestParam(value="delete",defaultValue="0") Integer delete,
	@RequestParam(value = "title", defaultValue = "") String title,
	@RequestParam(value = "content", defaultValue = "") String content,
	HttpSession session,
	@PathVariable("id") Integer id,
	Model model  ) {
		if(Login.checkAdminLogin(session)=="0")
			return JSP_LOGIN;
		Announcement e = announcementService.findById(id);
		BookEntity book = bookService.findOne(e.getBookId());
		try {
			if(edit>0){
				e.setTitle(title);
				e.setContents(content);
				e.setUpdateDate(new Date());
				Announcement ok = announcementService.update(e);
				e = announcementService.update(e);
				return "redirect:/admin/book/detail/"+book.getId();
			}
			if(delete>0){
				Announcement announcement = announcementService.findById(id);
				announcement.setIsDelete(1);
				announcementService.update(announcement);
				return "redirect:/admin/book/detail/"+book.getId();
			}
			model.addAttribute("book", book);
			model.addAttribute("e", e);
			return JSP_EDIT;
		} catch(Exception ex) {
			return JSP_LIST;
		}
	}
	//Decription: Create announcement
	//Url: http://kwebsosul.com/admin/announcement/create
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(
			@RequestParam(value="create",defaultValue="0") Integer create,
			HttpSession session,
			Model model) {
		log("Action 'create'");
		if(Login.checkAdminLogin(session)=="0")
			return JSP_LOGIN;
		try {
			if(create>0){
			Announcement announcement = new Announcement();
			announcement.setUpdateDate(new Date());
			announcement.setCreateDate(new Date());
			announcementService.create(announcement);
			}
			return JSP_LIST;
		} catch(Exception e) {
			
			return JSP_CREATE;
		}
	}

	

}
