/*
 * Created on 22 Dec 2015 ( Time 09:23:11 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.webbook.web.admin.controller;

import java.util.List;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;

import javax.annotation.Resource;
import javax.imageio.ImageIO;
import javax.imageio.ImageReader;
import javax.imageio.stream.ImageInputStream;
import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import javax.validation.Valid;

import org.apache.commons.io.FilenameUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.trams.webbook.web.common.AbstractController;
import org.trams.webbook.web.common.FileUtils;
import org.trams.webbook.web.common.FormMode;
import org.trams.webbook.web.common.Pager;
import org.trams.webbook.web.common.Login;
import org.trams.webbook.web.common.Message;
import org.trams.webbook.web.common.MessageType;
import org.trams.webbook.bean.jpa.BannerEntity;

//--- Entities
import org.trams.webbook.bean.Banner;

//--- Services 
import org.trams.webbook.business.service.BannerService;


/**
 * Spring MVC controller for 'Banner' management.
 */
@Controller
@RequestMapping("/admin/banner")
public class BannerAdminController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "banner";
	private static final String MAIN_LIST_NAME = "list";

	private static final String TOTAL_PAGE   = "pages";

	private static final String CURRENT_PAGE   = "pageNumber";

	private static final String LIST_PAGES   = "listPages";

	private static final Integer PAGE_SIZE   = 15;

	private static String nav = "banner";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_CREATE   = "admin/banner/create";
	private static final String JSP_BANNER   = "admin/banner";
	private static final String JSP_PAGING   = "admin/banner";
	private static final String JSP_EDIT   = "admin/banner/edit";
	private static final String JSP_DETAIL   = "admin/banner/detail";
	private static final String JSP_LOGIN   = "redirect:/admin/login";

	//--- Main entity service
	@Resource
    private BannerService bannerService; // Injected by Spring
	//--- Other service(s)
	@Autowired
	ServletContext servletContext;
	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public BannerAdminController() {
		super(BannerAdminController.class, MAIN_ENTITY_NAME );
		log("BannerAdminController created.");
	}
	//Decription: Show all banner
	//Url: http://kwebsosul.com/admin/banner
	@RequestMapping(value="", method = RequestMethod.GET)
	public String get(
			HttpSession session,
			Model model) {
		if(Login.checkAdminLogin(session)=="0")
			return JSP_LOGIN;
		List<Banner> listPage = null;
		listPage=bannerService.findAll();
		Banner b=new Banner();
		if(listPage!=null && listPage.size()>0){
			b=listPage.get(0);
			if(b.getBanner1()!=null){
				model.addAttribute("filename1", FilenameUtils.getBaseName(b.getBanner1())+"."+FilenameUtils.getExtension(b.getBanner1()));	
			}
			if(b.getBanner2()!=null){
				model.addAttribute("filename2", FilenameUtils.getBaseName(b.getBanner2())+"."+FilenameUtils.getExtension(b.getBanner2()));	
			}
			if(b.getBanner3()!=null){
				model.addAttribute("filename3", FilenameUtils.getBaseName(b.getBanner3())+"."+FilenameUtils.getExtension(b.getBanner3()));	
			}
		}
		model.addAttribute("b", b);	
		model.addAttribute("activePage", nav);
		return JSP_BANNER;
	}
	
	@RequestMapping(value="", method = RequestMethod.POST)
	public String post(
			@RequestParam(value = "file1") MultipartFile file1,
			@RequestParam(value = "file2") MultipartFile file2,
			@RequestParam(value = "file3") MultipartFile file3,
			HttpSession session,
			Model model) {
		if(Login.checkAdminLogin(session)=="0")
			return JSP_LOGIN;
		List<Banner> listPage = null;
		listPage=bannerService.findAll();
		Banner b=new Banner();
		if(listPage!=null && listPage.size()>0){
			b=listPage.get(0);
		}
		if(file1.getSize()>0){
			b.setBanner1(FileUtils.saveFileOrigin(file1, servletContext));  
		}
		if(file2.getSize()>0){
			b.setBanner2(FileUtils.saveFileOrigin(file2, servletContext));  
		}
		if(file3.getSize()>0){
			b.setBanner3(FileUtils.saveFileOrigin(file3, servletContext));  
		}
		if(listPage!=null && listPage.size()>0){
			bannerService.update(b);
		}else{
			b.setCreateDate(new Date());
			b.setUpdateDate(new Date());
			bannerService.create(b);
		}
		return "redirect:/admin/banner";
	}

	
	
}
