/*
 * Created on 22 Dec 2015 ( Time 09:23:11 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.webbook.web.admin.controller;

import java.util.List;
import java.util.ArrayList;
import java.util.Date;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import javax.validation.Valid;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.trams.webbook.web.common.AbstractController;
import org.trams.webbook.web.common.FormMode;
import org.trams.webbook.web.common.Pager;
import org.trams.webbook.web.common.Login;
import org.trams.webbook.web.common.Message;
import org.trams.webbook.web.common.MessageType;
import org.trams.webbook.bean.jpa.CommentEntity;

//--- Entities
import org.trams.webbook.bean.Comment;

//--- Services 
import org.trams.webbook.business.service.CommentService;
import org.trams.webbook.business.service.mapping.CommentServiceMapper;


/**
 * Spring MVC controller for 'Comment' management.
 */
@Controller
@RequestMapping("/admin/comment")
public class CommentAdminController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "comment";
	private static final String MAIN_LIST_NAME = "list";

	private static final String TOTAL_PAGE   = "pages";

	private static final String CURRENT_PAGE   = "pageNumber";

	private static final String LIST_PAGES   = "listPages";

	private static final Integer PAGE_SIZE   = 15;

	private static String nav = "comment";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_CREATE   = "admin/comment/create";
	private static final String JSP_LIST   = "admin/comment/list";
	private static final String JSP_PAGING   = "admin/comment";
	private static final String JSP_EDIT   = "admin/comment/edit";
	private static final String JSP_DETAIL   = "admin/comment/detail";
	private static final String JSP_LOGIN   = "redirect:/admin/login";

	//--- Main entity service
	@Resource
    private CommentService commentService; // Injected by Spring
	//--- Other service(s)
	@Resource
	private CommentServiceMapper commentServiceMapper;

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public CommentAdminController() {
		super(CommentAdminController.class, MAIN_ENTITY_NAME );
		log("CommentAdminController created.");
	}

	@RequestMapping("/list")
	public String list(
			@RequestParam(value="page",defaultValue="1") Integer page,
			@RequestParam(value="type",defaultValue="id") String type,
			@RequestParam(value="key",defaultValue="") String key,
			HttpSession session,
			Model model) {
		if(Login.checkAdminLogin(session)=="0")
			return JSP_LOGIN;
		Page<CommentEntity> listPage = null;
		listPage=commentService.findAll(page);
		model.addAttribute(MAIN_LIST_NAME, listPage);	
		model.addAttribute("key", key);
		model.addAttribute("type", type);
		model.addAttribute("activePage", nav);
		model.addAttribute("pagination_navigator", "/comment/list");
		new Pager<CommentEntity>(listPage).setSetting(model, "type="+type+"&amp;key="+key+"&amp;");		
		return JSP_LIST;
	}

	
	@RequestMapping("/detail/{id}")
	public String detail(
	Model model,
	HttpSession session, 
	@PathVariable("id") Integer id) {
		if(Login.checkAdminLogin(session)=="0")
			return JSP_LOGIN;
		Comment comment = commentService.findById(id);
		model.addAttribute("comment", comment);
		return JSP_DETAIL;
	}
	
	@RequestMapping(value = "/edit/{id}")
	public String update(
	@RequestParam(value="edit",defaultValue="0") Integer edit,
	@RequestParam(value="comment_text",defaultValue="") String comment_text,
	HttpSession session,
	@PathVariable("id") Integer id,
	Model model  ) {
	if(Login.checkAdminLogin(session)=="0")
			return JSP_LOGIN;
	CommentEntity commentEntity = commentService.findByOne(id);
		try {
			if(edit>0){
				Comment comment=commentServiceMapper.mapCommentEntityToComment(commentEntity);
				comment = commentService.update(comment);
				comment.setUpdateDate(new Date());
				comment.setComment(comment_text);
				commentService.update(comment);
				commentEntity = commentService.findByOne(id);
			}
			model.addAttribute("item", commentEntity);
			return JSP_EDIT;
		} catch(Exception e) {
			return JSP_LIST;
		}
	}
	
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(
			@RequestParam(value="create",defaultValue="0") Integer create,
			HttpSession session,
			Model model) {
		log("Action 'create'");
		if(Login.checkAdminLogin(session)=="0")
			return JSP_LOGIN;
		try {
			if(create>0){
			Comment comment = new Comment();
			
			comment.setUpdateDate(new Date());
			comment.setCreateDate(new Date());
			commentService.create(comment);
			}
			return JSP_LIST;
		} catch(Exception e) {
			
			return JSP_CREATE;
		}
	}



}
