/*
 * Created on 15 Dec 2015 ( Time 14:50:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.webbook.web.common;

public interface ListItem {

	public String getValue();
	
	public String getLabel();
}
