/*
 * Created on 11 Jan 2016 ( Time 16:14:47 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.webbook.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Category implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 200 )
    private String catname;

    @Size( max = 200 )
    private String description;


    private Integer groupid;

    @Size( max = 200 )
    private String groupname;


    private Integer catid;

    @Size( max = 500 )
    private String image;


    private Date createdate;


    private Date updatedate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setCatname( String catname ) {
        this.catname = catname;
    }
    public String getCatname() {
        return this.catname;
    }

    public void setDescription( String description ) {
        this.description = description;
    }
    public String getDescription() {
        return this.description;
    }

    public void setGroupid( Integer groupid ) {
        this.groupid = groupid;
    }
    public Integer getGroupid() {
        return this.groupid;
    }

    public void setGroupname( String groupname ) {
        this.groupname = groupname;
    }
    public String getGroupname() {
        return this.groupname;
    }

    public void setCatid( Integer catid ) {
        this.catid = catid;
    }
    public Integer getCatid() {
        return this.catid;
    }

    public void setImage( String image ) {
        this.image = image;
    }
    public String getImage() {
        return this.image;
    }

    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    public void setUpdatedate( Date updatedate ) {
        this.updatedate = updatedate;
    }
    public Date getUpdatedate() {
        return this.updatedate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(catname);
        sb.append("|");
        sb.append(description);
        sb.append("|");
        sb.append(groupid);
        sb.append("|");
        sb.append(groupname);
        sb.append("|");
        sb.append(catid);
        sb.append("|");
        sb.append(image);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(updatedate);
        return sb.toString(); 
    } 


}
