/*
 * Created on 4 Mar 2016 ( Time 14:07:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.webbook.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Post implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Integer userId;

    @Size( max = 300 )
    private String title;


    private Integer bulletinId;

    @Size( max = 50 )
    private String bulletinName;

    @Size( max = 500 )
    private String image1;

    @Size( max = 500 )
    private String image2;

    @Size( max = 2147483647 )
    private String contents;

    @Size( max = 500 )
    private String file1;

    @Size( max = 500 )
    private String file2;

    @Size( max = 500 )
    private String filename1;

    @Size( max = 500 )
    private String filename2;


    private Integer reportNumber;


    private Integer viewsNumber;


    private Integer isDelete;


    private Date updateDate;


    private Date createDate;


    private Integer bookId;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUserId( Integer userId ) {
        this.userId = userId;
    }
    public Integer getUserId() {
        return this.userId;
    }

    public void setTitle( String title ) {
        this.title = title;
    }
    public String getTitle() {
        return this.title;
    }

    public void setBulletinId( Integer bulletinId ) {
        this.bulletinId = bulletinId;
    }
    public Integer getBulletinId() {
        return this.bulletinId;
    }

    public void setBulletinName( String bulletinName ) {
        this.bulletinName = bulletinName;
    }
    public String getBulletinName() {
        return this.bulletinName;
    }

    public void setImage1( String image1 ) {
        this.image1 = image1;
    }
    public String getImage1() {
        return this.image1;
    }

    public void setImage2( String image2 ) {
        this.image2 = image2;
    }
    public String getImage2() {
        return this.image2;
    }

    public void setContents( String contents ) {
        this.contents = contents;
    }
    public String getContents() {
        return this.contents;
    }

    public void setFile1( String file1 ) {
        this.file1 = file1;
    }
    public String getFile1() {
        return this.file1;
    }

    public void setFile2( String file2 ) {
        this.file2 = file2;
    }
    public String getFile2() {
        return this.file2;
    }

    public void setFilename1( String filename1 ) {
        this.filename1 = filename1;
    }
    public String getFilename1() {
        return this.filename1;
    }

    public void setFilename2( String filename2 ) {
        this.filename2 = filename2;
    }
    public String getFilename2() {
        return this.filename2;
    }

    public void setReportNumber( Integer reportNumber ) {
        this.reportNumber = reportNumber;
    }
    public Integer getReportNumber() {
        return this.reportNumber;
    }

    public void setViewsNumber( Integer viewsNumber ) {
        this.viewsNumber = viewsNumber;
    }
    public Integer getViewsNumber() {
        return this.viewsNumber;
    }

    public void setIsDelete( Integer isDelete ) {
        this.isDelete = isDelete;
    }
    public Integer getIsDelete() {
        return this.isDelete;
    }

    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setBookId( Integer bookId ) {
        this.bookId = bookId;
    }
    public Integer getBookId() {
        return this.bookId;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(title);
        sb.append("|");
        sb.append(bulletinId);
        sb.append("|");
        sb.append(bulletinName);
        sb.append("|");
        sb.append(image1);
        sb.append("|");
        sb.append(image2);
        // attribute 'contents' not usable (type = String Long Text)
        sb.append("|");
        sb.append(file1);
        sb.append("|");
        sb.append(file2);
        sb.append("|");
        sb.append(filename1);
        sb.append("|");
        sb.append(filename2);
        sb.append("|");
        sb.append(reportNumber);
        sb.append("|");
        sb.append(viewsNumber);
        sb.append("|");
        sb.append(isDelete);
        sb.append("|");
        sb.append(updateDate);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(bookId);
        return sb.toString(); 
    } 


}
