/*
 * Created on 13 Jan 2016 ( Time 11:09:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.webbook.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class ProfitRefund implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Integer userId;


    private Double depositAmount;

    @Size( max = 300 )
    private String name;

    @Size( max = 300 )
    private String residentNumber;

    @Size( max = 15 )
    private String cellPhone;

    @Size( max = 300 )
    private String email;

    @Size( max = 300 )
    private String address;

    @Size( max = 300 )
    private String accountHolderName;

    @Size( max = 200 )
    private String relationship;


    private Integer bankId;

    @Size( max = 200 )
    private String bankName;

    @Size( max = 200 )
    private String accountNumber;


    private Date applicationDate;


    private Date depositDate;


    private Integer deposited;


    private Integer isDelete;


    private Date updateDate;


    private Date createDate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUserId( Integer userId ) {
        this.userId = userId;
    }
    public Integer getUserId() {
        return this.userId;
    }

    public void setDepositAmount( Double depositAmount ) {
        this.depositAmount = depositAmount;
    }
    public Double getDepositAmount() {
        return this.depositAmount;
    }

    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    public void setResidentNumber( String residentNumber ) {
        this.residentNumber = residentNumber;
    }
    public String getResidentNumber() {
        return this.residentNumber;
    }

    public void setCellPhone( String cellPhone ) {
        this.cellPhone = cellPhone;
    }
    public String getCellPhone() {
        return this.cellPhone;
    }

    public void setEmail( String email ) {
        this.email = email;
    }
    public String getEmail() {
        return this.email;
    }

    public void setAddress( String address ) {
        this.address = address;
    }
    public String getAddress() {
        return this.address;
    }

    public void setAccountHolderName( String accountHolderName ) {
        this.accountHolderName = accountHolderName;
    }
    public String getAccountHolderName() {
        return this.accountHolderName;
    }

    public void setRelationship( String relationship ) {
        this.relationship = relationship;
    }
    public String getRelationship() {
        return this.relationship;
    }

    public void setBankId( Integer bankId ) {
        this.bankId = bankId;
    }
    public Integer getBankId() {
        return this.bankId;
    }

    public void setBankName( String bankName ) {
        this.bankName = bankName;
    }
    public String getBankName() {
        return this.bankName;
    }

    public void setAccountNumber( String accountNumber ) {
        this.accountNumber = accountNumber;
    }
    public String getAccountNumber() {
        return this.accountNumber;
    }

    public void setApplicationDate( Date applicationDate ) {
        this.applicationDate = applicationDate;
    }
    public Date getApplicationDate() {
        return this.applicationDate;
    }

    public void setDepositDate( Date depositDate ) {
        this.depositDate = depositDate;
    }
    public Date getDepositDate() {
        return this.depositDate;
    }

    public void setDeposited( Integer deposited ) {
        this.deposited = deposited;
    }
    public Integer getDeposited() {
        return this.deposited;
    }

    public void setIsDelete( Integer isDelete ) {
        this.isDelete = isDelete;
    }
    public Integer getIsDelete() {
        return this.isDelete;
    }

    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(depositAmount);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(residentNumber);
        sb.append("|");
        sb.append(cellPhone);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(address);
        sb.append("|");
        sb.append(accountHolderName);
        sb.append("|");
        sb.append(relationship);
        sb.append("|");
        sb.append(bankId);
        sb.append("|");
        sb.append(bankName);
        sb.append("|");
        sb.append(accountNumber);
        sb.append("|");
        sb.append(applicationDate);
        sb.append("|");
        sb.append(depositDate);
        sb.append("|");
        sb.append(deposited);
        sb.append("|");
        sb.append(isDelete);
        sb.append("|");
        sb.append(updateDate);
        sb.append("|");
        sb.append(createDate);
        return sb.toString(); 
    } 


}
